// @generated by ollama-canary-D4-2026-05-10

import Fuse from 'fuse.js';
import fs from 'node:fs';
import path from 'node:path';

interface CandidateExercise {
  id: string;
  name: string;
  bodyPart?: string;
  equipment?: string;
  target?: string;
}

interface MatchResult {
  unmappedId: string;
  bestMatchId: string | null;
  bestMatchName: string | null;
  score: number;
  decision: 'auto-accept' | 'manual-review' | 'no-match';
}

async function main() {
  if (process.argv.length < 3) {
    console.error('usage: tsx scripts/fuzzy-match-exercises.ts <catalogue.json>');
    process.exit(1);
  }

  const cataloguePath = path.resolve(process.cwd(), process.argv[2]);
  let unmappedIds: string[] = ['demo-bench-press', 'demo-squat', 'demo-row'];

  if (process.argv.length > 3) {
    const unmappedIdsPath = path.resolve(process.cwd(), process.argv[3]);
    try {
      unmappedIds = JSON.parse(fs.readFileSync(unmappedIdsPath, 'utf8'));
    } catch (e) {
      console.error('usage: tsx scripts/fuzzy-match-exercises.ts <catalogue.json>');
      process.exit(1);
    }
  }

  let catalogue: CandidateExercise[] = [];
  try {
    catalogue = JSON.parse(fs.readFileSync(cataloguePath, 'utf8'));
  } catch (e) {
    console.error('usage: tsx scripts/fuzzy-match-exercises.ts <catalogue.json>');
    process.exit(1);
  }

  const fuse = new Fuse<CandidateExercise>(catalogue, {
    keys: ['name'],
    threshold: 0.4,
    includeScore: true,
    ignoreLocation: true,
  });

  let autoAcceptCount = 0;
  let manualReviewCount = 0;
  let noMatchCount = 0;

  for (const unmappedId of unmappedIds) {
    const searchQuery = unmappedId.replace(/-/g, ' ');
    const result = fuse.search(searchQuery);

    let bestMatch: { item: CandidateExercise; score: number } | null = null;
    if (result.length > 0) {
      const top = result[0];
      bestMatch = { item: top.item, score: top.score ?? 1 };
    }

    let decision: MatchResult['decision'] = 'no-match';
    let score: number = bestMatch ? bestMatch.score : 1;

    if (score < 0.3) {
      decision = 'auto-accept';
      autoAcceptCount++;
    } else if (score >= 0.3 && score <= 0.6) {
      decision = 'manual-review';
      manualReviewCount++;
    } else {
      noMatchCount++;
    }

    const matchResult: MatchResult = {
      unmappedId,
      bestMatchId: bestMatch ? bestMatch.item.id : null,
      bestMatchName: bestMatch ? bestMatch.item.name : null,
      score,
      decision,
    };

    console.log(JSON.stringify(matchResult));
  }

  console.error(`summary: ${autoAcceptCount} auto-accept, ${manualReviewCount} manual-review, ${noMatchCount} no-match (total ${unmappedIds.length})`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
