// @generated by ollama-canary-2026-05-10

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { exerciseLibraryMap } from '@/lib/exercises';
import { exerciseAnimationMap } from '@/lib/exerciseAnimations';

describe('exerciseAnimations', () => {
  it('every animation map key maps to a non-empty https URL', () => {
    for (const [key, value] of Object.entries(exerciseAnimationMap)) {
      assert(typeof value === 'string' && value.length > 0, `Value for key ${key} is not a non-empty string`);
      assert(/^https?:\/\//.test(value), `Value for key ${key} does not match https URL pattern`);
    }
  });

  it('every animation map key corresponds to a real exercise id', () => {
    for (const key of Object.keys(exerciseAnimationMap)) {
      assert(exerciseLibraryMap.has(key), `Key ${key} is not present in exerciseLibraryMap`);
    }
  });

  it('every exercise id is either mapped or marked AI-FALLBACK', async () => {
    const animationSource = fs.readFileSync(path.resolve('src/lib/exerciseAnimations.ts'), 'utf-8');
    const uncoveredIds: string[] = [];

    for (const [id] of exerciseLibraryMap) {
      if (!exerciseAnimationMap[id]) {
        if (!animationSource.includes(`'${id}': // AI-FALLBACK`)) {
          uncoveredIds.push(id);
        }
      }
    }

    assert(uncoveredIds.length === 0, `Uncovered ids: ${uncoveredIds.join(', ')}`);
  });
});
